import { UserRole } from '@/enum/user.enum';

export const FIELDS_BY_ROLE: Record<UserRole, string[]> = {
  [UserRole.ADMIN]: [
    'user_id',
    'fullname',
    'role',
    'date_of_birth',
    'citizen_id',
    'address',
    'is_active',
  ],
  [UserRole.TEACHER]: [
    'user_id',
    'fullname',
    'role',
    'date_of_birth',
    'citizen_id',
    'address',
    'education_level',
    'professional_level',
    'pedagogy_level',
    'teaching_subject',
    'teacher_certificate_number',
    'teacher_certificate_issue_date',
    'teacher_certificate_issue_place',
    'health_certificate_number',
    'health_certificate_expiry_date',
    'recruitment_type',
    'contract_number',
    'contract_signed_date',
    'contract_expiry_date',
    'is_active',
  ],
  [UserRole.USER]: [
    'user_id',
    'fullname',
    'role',
    'date_of_birth',
    'citizen_id',
    'address',
    'is_active',
  ],
};